### ISSUE TITLE
Gatewayd container exits unsuccessfully on v0.9.6 

### ISSUE THREAD

**Issue by eabasir** [gatewayd-io/gatewayd#568] opened 2024-06-08 15:38 UTC
## Expected Behavior
docker-compose should start the `gatewayd` container without any problems.

## Current Behavior
After the release v0.9.6 the `gatewayd` container exits unsuccessfully (exit code 1) due to failure at parsing the  `actionRedis` config.

## Failure Information (for bugs)
The failiure only occurs when running the latest version (0.9.6) in a docker container as described below. It doesn't show any errors after building and running the project locally (`go build main.go && ./main run`) 

## Steps to Reproduce

1. Try running the `docker-compose up` which by default uses the version 0.9.6
2. Notice the aforementioned failure 
3. Uncomment the `GATEWAYD_VERSION` env var for the `gatewayd` service in the docker-compose.yaml file and change the version to 0.9.5
4. Run the `docker-compose up` again. The container should start successfully.  

## Context

- Operating System and architecture: MacOS 14.4.1 (Sonoma), Apple M3 Pro
- GatewayD version: 0.9.6
- Docker version: 24.0.7
- Docker compose version: v2.23.3-desktop.2
- 
## Failure Logs

![image](https://github.com/gatewayd-io/gatewayd/assets/20037417/cd1a7003-914c-413a-b03d-20443169cd35)

**Comment by mostafa** [comment] 2024-06-08 19:45
@eabasir I couldn't reproduce it on my machine. It just works.

**Comment by sinadarbouy** [comment] 2024-06-09 16:04
yes, I can reproduce this issue. It seems, as you said, there is a problem with the `actionRedis` parsing in the plugin config.

**Comment by eabasir** [comment] 2024-06-09 17:44
There is no issue with the ARM binary that is being executed locally, though. The main issue is when the linux-arm64 binary is used in a docker container.

**Comment by eabasir** [comment] 2024-06-09 19:53
Some more inputs:
I build the docker file locally and start it. It starts successfully, however I've noticed that the `git=2.45.1-r0` is no longer available in the apk repository. To build the image I had to update the Dockerfile to `git=2.45.1-r0`

**Comment by mostafa** [comment] 2024-06-09 20:07
@eabasir `git` was recently updated by @sinadarbouy and is available on the `main` branch.

**Comment by mostafa** [comment] 2024-10-01 20:38
@eabasir @sinadarbouy Can you test this again with the latest version to see if it is still reproducible? I couldn't reproduce this again.

**Comment by sinadarbouy** [comment] 2024-10-02 13:28
> @eabasir @sinadarbouy Can you test this again with the latest version to see if it is still reproducible? I couldn't reproduce this again.

@mostafa Yes, we still have this issue. It seems to only appear on ARM machines.
```
2024-10-02 15:22:50 2024/10/02 13:22:50 linting failed, OriginalError: jsonschema: '/clients/default' does not validate with https://github.com/gatewayd-io/gatewayd/config/global-config#/$ref/properties/clients/additionalProperties/$ref/additionalProperties: additionalProperties 'writes', 'reads' not allowed
2024-10-02 15:24:26 2024/10/02 13:24:26 linting failed, OriginalError: jsonschema: '/clients/default' does not validate with https://github.com/gatewayd-io/gatewayd/config/global-config#/$ref/properties/clients/additionalProperties/$ref/additionalProperties: additionalProperties 'writes', 'reads' not allowed
```
I’ll take a look later today and see if I can sort it out.

**Comment by sinadarbouy** [comment] 2024-10-02 19:58
> > @eabasir @sinadarbouy Can you test this again with the latest version to see if it is still reproducible? I couldn't reproduce this again.
> 
> @mostafa Yes, we still have this issue. It seems to only appear on ARM machines.
> 
> ```
> 2024-10-02 15:22:50 2024/10/02 13:22:50 linting failed, OriginalError: jsonschema: '/clients/default' does not validate with https://github.com/gatewayd-io/gatewayd/config/global-config#/$ref/properties/clients/additionalProperties/$ref/additionalProperties: additionalProperties 'writes', 'reads' not allowed
> 2024-10-02 15:24:26 2024/10/02 13:24:26 linting failed, OriginalError: jsonschema: '/clients/default' does not validate with https://github.com/gatewayd-io/gatewayd/config/global-config#/$ref/properties/clients/additionalProperties/$ref/additionalProperties: additionalProperties 'writes', 'reads' not allowed
> ```
> 
> I’ll take a look later today and see if I can sort it out.

I checked it again, and it looks like the issue was caused by using the `latest` tag in Docker Compose. Docker Compose didn’t recognize the image update, so it used the local one instead. After I removed the local image with
```bash
docker image rmi gatewaydio/gatewayd:latest
```
 it got fixed. So the problem’s gone, and we can close this task now.
 
 For future releases, we should probably use a specific release tag in Docker Compose instead of `latest`.

**Comment by mostafa** [comment] 2024-10-02 20:01
@sinadarbouy How about adding `pull_policy: always` to the GatewayD image, so every time you run it, it'll pull the _actual_ latest version, rather than the existing one?

**Comment by sinadarbouy** [comment] 2024-10-02 20:19
> pull_policy: always

Yeah, using `pull_policy` is a good idea 👍. It’ll always pull the latest image, but there’s a chance we could hit the [rate limit](https://docs.docker.com/docker-hub/download-rate-limit/#whats-the-download-rate-limit-on-docker-hub).

**Closed** 2024-10-02 21:31 UTC
Labels: bug
